export const conferences = [
    {
        id: 1,
        topic: null,
        author: {
            id: 2,
            firstName: 'Asd',
            lastName: "asd",
            birthday: null,
            bioDetails: null,
        },
        startDate: null,
        endDate: null,
        description: 'description description description description description description description description descriptiondescription description descriptiondescription description',
        notifications: [],
        users: [],
        presentations: [],
    },
    {
        id: 2,
        topic: null,
        author: {
            id: 2,
            firstName: 'Asd',
            lastName: "asd",
            birthday: null,
            bioDetails: null,
        },
        startDate: null,
        endDate: null,
        description: null,
        notifications: [],
        users: [],
        presentations: [],
    },
    {
        id: 3,
        topic: null,
        author: {
            id: 2,
            firstName: 'Asd',
            lastName: "asd",
            birthday: null,
            bioDetails: null,
        },
        startDate: null,
        endDate: null,
        description: null,
        notifications: [],
        users: [],
        presentations: [],
    },
    {
        id: 4,
        topic: null,
        author: {
            id: 2,
            firstName: 'Asd',
            lastName: "asd",
            birthday: null,
            bioDetails: null,
        },
        startDate: null,
        endDate: null,
        description: null,
        notifications: [],
        users: [],
        presentations: [],
    },
    {
        id: 5,
        topic: null,
        author: {
            id: 2,
            firstName: 'Asd',
            lastName: "asd",
            birthday: null,
            bioDetails: null,
        },
        startDate: null,
        endDate: null,
        description: null,
        notifications: [],
        users: [],
        presentations: [],
    },
    {
        id: 6,
        topic: null,
        author: {
            id: 2,
            firstName: 'Asd',
            lastName: "asd",
            birthday: null,
            bioDetails: null,
        },
        startDate: null,
        endDate: null,
        description: null,
        notifications: [],
        users: [],
        presentations: [],
    },
    {
        id: 7,
        topic: null,
        author: {
            id: 2,
            firstName: 'Asd',
            lastName: "asd",
            birthday: null,
            bioDetails: null,
        },
        startDate: null,
        endDate: null,
        description: null,
        notifications: [],
        users: [],
        presentations: [],
    },

]